---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3000279935-XR55UwXBCMQXI5JqwPq8DMDJZ6xfQ91XweQFSnW
:access_token_secret: KdYCJjgFhSR3yAyCQ8wEN91tSEbG1BP2dcOLhN1ueAJCN
